sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'ppa:beineri/opt-qt571-trusty'
          packages:
            - g++-4.9
            - qt57base
            - qt57xmlpatterns
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - os: osx
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
  
branches:
  except:
    - documentation

before_install:
 - eval "${MATRIX_EVAL}"
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

install:
  - cmake --version
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt57/bin/qt57-env.sh; fi
  - mkdir build
  - cd build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake .. ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake .. -DCMAKE_PREFIX_PATH=/usr/local/opt/qt ; fi
  - make
  - make package
